GET http://localhost:8000/user/get
Accept: application/json
Authorization: Basic test test

###
POST http://localhost:8000/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###
POST http://localhost:8000/user/register
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###
GET http://localhost:8000/user/test
Accept: application/json
